### ISSUE TITLE
Suggestion: Add information on how to properly use the plugin

### ISSUE THREAD

**Issue by pgirzalsky** [CharlieEtienne/custom-links-in-elementor-image-carousel#1]
I just saw this feedback on your plugin: https://wordpress.org/support/topic/does-not-work-1401/

I was confused myself first, when I installed the plugin and set a link for my image. The documentation & how to use section does not explain that you have to enable the option "Link" in the Image Carousel widget and set it to: "Media Files" in order for it to work.

Maybe add that so the users aren't confused and think that your plugin is not working :)

**Comment by CharlieEtienne** [comment]
You're right, I will add some more information.

Thank you

**Comment by CharlieEtienne** [comment]
Done in 1.0.1
