### ISSUE TITLE
The plugin crashes the page on which it is used

### ISSUE THREAD

**Issue by aashjain104** [CharlieEtienne/custom-links-in-elementor-image-carousel#2]
Hello author,
I found this plugin very helpful but unfortunately it crashed my webpage on which I was using it. Can you please have a look into it and fix it?

This is a really helpful plugin that I am looking forward to use on many sites.

To fix it and present my website to the client, I have removed the plugin but I want to use it. It would be great if you could fix it asap.

Thanks

**Comment by CharlieEtienne** [comment]
Hi @aashjain104,

I'm sorry but I missed this thread. Do you still have this issue?

Charlie

**Comment by surflibre** [comment]
Hi, 
I've got the same request than aashjain104, pluggin crash my website (only restore pages works, or disable plugin) : 
"Got error 'PHP message: PHP Fatal error:  Uncaught TypeError: Return value of CustomLinksEICW::get_image_caption() must be of the type string, null returned in custom-links-in-elementor-image-carousel/custom-links-in-elementor-image-carousel.php:275
custom-links-in-elementor-image-carousel/custom-links-in-elementor-image-carousel.php(133): CustomLinksEICW->get_image_caption()\n#1 /wp-includes/class-wp-hook.php(308): CustomLinksEICW->widget_content()"

Regards,

**Comment by surflibre** [comment]
Hi,
I'll be back sooner than expected. I commented out line 133 like this :
// $image_caption = $this->get_image_caption( $attachment, $widget );
and now it works..
But I would have preferred a less hassle solution if possible...

**Comment by CharlieEtienne** [comment]
Hi @aashjain104 & @surflibre,

I just pushed a fix in version 1.1.1, could you update and let me know if it works fine now?

Thanks,

Charlie

**Comment by surflibre** [comment]
Hi,
Ok the ":string"(265), it works.
Thanks and good job,
Regards,
